project:
  name: CoshKey Tree API
  debug: true
  environment: development

rest:
  host: 0.0.0.0
  port: 8080

database:
  host: localhost
  port: 5432
  user: postgres
  password: postgres
  name: coshkey
  sslmode: disable
  driver: pgx