project:
  name: CoshKey API
  debug: true
  environment: development
  coshkeyUrl: http://coshkey.local
  coshkeyToken: qwerty

rest:
  host: 0.0.0.0
  port: 8080
  writeTimeout: 60 # Seconds
  readTimeout: 0 # Seconds

database:
  host: localhost
  port: 5432
  user: postgres
  password: postgres
  name: coshkey_prod
  sslmode: disable