version: "3.9"

services:
  coshkey-tree-api:
    build:
      context: .
      dockerfile: Dockerfile
    restart: unless-stopped
    ports:
      - 8080:8080 # Rest
    volumes:
      - ./config.yml:/root/config.yml