version: "3.9"

services:
  coshkey_api:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: coshkey_api
    restart: unless-stopped
    ports:
      - "8080:8080"
    network_mode: "host"
    volumes:
      - ./config.yml:/opt/project/config.yml